/* eslint-disable no-unused-vars */
const clothes = [
    {
        id:        0,
        isNew:     false,
        title:     'Джинсы "Зимой и летом одним цветом"',
        price:     290,
        img:       'src/assets/img/jeans-img.png',
        isClothes: true,
        details:   'Обычные синие джинсы. Материал: Деним 100%',
    },
    {
        id:        1,
        isNew:     false,
        title:     'Свитшот "Простенько и со вкусом"',
        price:     270,
        img:       'src/assets/img/big-img.png',
        isClothes: true,
        details:   'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
    },
    {
        id:        2,
        isNew:     true,
        title:     'Свитер "Чистый код"',
        price:     180,
        img:       'src/assets/img/sweater-img.png',
        isClothes: true,
        details:   'Брендированный свитер от Robert Martin. Материал: Синтетика 100%',
    },
    {
        id:        3,
        isNew:     false,
        title:     'Футболка "Эволюционируй или сдохни"',
        price:     220,
        img:       'src/assets/img/item-img.png',
        isClothes: true,
        details:   'Брендированная футболка от Qazaq Republic. Материал: Хлопок 90%, Вискоза 10%',
    },
    {
        id:        4,
        isNew:     false,
        title:     'Шапка "Просто сделай это"',
        price:     150,
        img:       'src/assets/img/beanie-img.jpg',
        isClothes: true,
        details:   'Брендированная шапка от Qazaq Republic. Материал: Хлопок 50%, Вискоза 50%',
    },
    {
        id:        5,
        isNew:     true,
        title:     'Джоггеры "Стильный программист"',
        price:     300,
        img:       'src/assets/img/trousers-img.png',
        isClothes: true,
        details:   'Брендированные джоггеры от China Republic. Материал: Хлопок 10%, Синтетика 90%',
    },
    {
        id:        6,
        isNew:     false,
        title:     'Кеды "Замшевоё всё"',
        price:     350,
        img:       'src/assets/img/sneakers-img.jpg',
        isClothes: true,
        details:   'Кеды от Levi`s',
    },
];

const accessories = [
    {
        id:        7,
        isNew:     true,
        title:     'Фирменная кружка',
        price:     240,
        img:       'src/assets/img/mug2-img.jpg',
        isClothes: false,
        details:   'Классная кружка',
    },
    {
        id:        8,
        isNew:     false,
        title:     'Белая кружка',
        price:     180,
        img:       'src/assets/img/mug-img.jpg',
        isClothes: false,
        details:   'Классная кружка',
    },
    {
        id:        9,
        isNew:     false,
        title:     'Бутылка для воды',
        price:     160,
        img:       'src/assets/img/bottle-img.png',
        isClothes: false,
        details:   'Классная бутылка',
    },
    {
        id:        10,
        isNew:     true,
        title:     'Бутылка для спорт-пита',
        price:     100,
        img:       'src/assets/img/bottle2-img.jpg',
        isClothes: false,
        details:   'Классная бутылка',
    },
    {
        id:        11,
        isNew:     false,
        title:     'Прозрачная бутылка',
        price:     80,
        img:       'src/assets/img/bottle1-img.png',
        isClothes: false,
        details:   'Классная бутылка',
    },
    {
        id:        12,
        isNew:     false,
        title:     'Кружка с принтом',
        price:     110,
        img:       'src/assets/img/mug1-img.jpg',
        isClothes: false,
        details:   'Классная кружка',
    },
];

export { clothes, accessories };
